- chat-v2-sample/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- chat-v2-sample/swift-chat-v2-sample/LoginViewController.swift
Update to v 2.5.3 and replace async isLoggedIn with sync isLoggedIn
> Update for synchronous isLoggedIn call

- chat-v2-sample/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- chat-v2-sample/swift-chat-v2-sample/GuestViewController.swift
- chat-v2-sample/swift-chat-v2-sample/OrderHistoryViewController.swift
Update sample app to use sdk version 2.7.1
> Update to 2.7.2

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KED-62475] Upgrading to latest version

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
New version of SDK was released (v4.0.2)
Our Sample app needs updated as a result
[KDEV-62654]
[KDEV-62654]: https://kustomer.atlassian.net/browse/KDEV-62654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KDEV-62654] Update Versions in Sample App

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Updating iOS SDK to latest version
> [KDEV-63323] Update versions to latest

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update SDK versions
[KDEV-63490]
[KDEV-63490]: https://kustomer.atlassian.net/browse/KDEV-63490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KDEV-63490] Update SDK Version

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KDEV-63902] Bumping versions to 4.1.3

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [hKDEV-64237] Bumping to 4.1.4

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Just bumping the Cocoapods and Remote SPM version of the SDK
> Bump versions

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KEDV-65800] Bump version

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Chore][KDEV-66511] Bump iOS versions

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Chore] Bump to 5.0.1

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Chore] Bumping to 5.0.2

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KDEV-67226] Bump to 5.0.3

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KDEV-67646] Bump to 5.0.4

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Chore][KDEV-68211] Bumping Sample app

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KDEV-69508] Bumping to 5.0.8

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KDEV-70468] Bump to 5.0.9

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Bumping samples to latest version
> [KDEV-71109] Bump to 5.0.10

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [KDEV-73810] Bump to 5.0.14

- chat-v2-sample/CocoaPods/Podfile
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.pbxproj
- chat-v2-sample/Remote-SPM/swift-chat-v2-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Chore] bump to 6.0.0
